### ISSUE TITLE
Confirmation: we're going to port all based types to openAPI schema, or not?

### ISSUE THREAD

**Issue by sarikanspotlight** [openEHR/sanbox-openapi#3]
@sebastian-iancu I'm looking at the yaml for `EHR_STATUS` and it has the following `properties` section:
```
properties:
  archetype_node_id:
    type: string
    example: openEHR-EHR-EHR_STATUS.generic.v1
  name:
    $ref: ../base_types/Name.yaml
  is_modifiable:
    type: boolean
    default: true
  is_queryable:
    type: boolean
    default: true
```

I think we'll have DV_TEXT defined in OpenAPI schema, and `$ref` for name should be pointing at that, right? That's what I had in mind, but I wanted to check with you and Pablo
